# Generated by Django 5.1.3 on 2024-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_remove_attendance_scanned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
