# Generated by Django 5.1.3 on 2024-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_scanned_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="scanned_at",
        ),
        migrations.AddField(
            model_name="attendance",
            name="checked_in_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отметки"
            ),
        ),
    ]
