# Generated by Django 5.1.3 on 2024-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_remove_attendance_scanned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="qr_hash",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="QR Хэш"
            ),
        ),
    ]
